#!/usr/bin/env python3

from matplotlib import cm, collections, colors, lines, patches, pyplot
import descartes
import json
import matplotlib
import os
import pandas
import pymongo
import shapely

import util

# data sources
SOURCES = "sources/"
SHELTERS_JSON = "%s/shelters.json" % SOURCES
ROUTES_JSON = "%s/shelter_routes.json" % SOURCES
BOSTON_GEOJSON = "%s/boston.geojson" % SOURCES

ACS5_CSV = "%s/acs5_2015_ma_subset.csv" % SOURCES
ACS5_GEOID_PREFIX = "15000US"
ACS5_POP_TOTAL_COL = "B01003e1"

BG_DB = "tiger_2016"
BG_COLLECTION = "blockgroups"

EVAC_DB = "massgis_mapserver"
EVAC_COLLECTION = "CityServices.Evacuation"
EVAC_EXCLUDE = ["ZONE A", "ZONE B", "ZONE C"]

# formatted data
OUTDIR = "analysis/"
UPDATED_ROUTES_TEMPLATE = "%s/routes_%%s_sorted.json" % OUTDIR
STATS_JSON_TEMPLATE = "%s/shelter_stats_%%s_%%s.json" % OUTDIR

# ignore
IGNORE_GEOIDS = [
    "250259901010", # ocean
    "250235001011" # hull
]

# appearance
COLORMAP = "YlOrRd"
#COLORMAP = "Paired"
#COLORMAP = "viridis_r"

COLOR_INACCESSIBLE = "#47365c"

SHELTER_COLOR = "#009999"
SHELTER_COLOR_EXCLUDED = "#009e00"
SHELTER_COLOR_UNUSED = "#1b1bb3"
SHELTER_MIN_SIZE = 2
SHELTER_MAX_SIZE = 5

SHELTER_LINK_COLOR = "#294040"
SHELTER_LINK_LINEWIDTH = 1
SHELTER_LINK_OPACITY = 0.1

LEGEND_MARKER_SIZE = 6

def update_routes():
    """ Add information to and organize the raw data generated by simulate.py
    """

    with open(SHELTERS_JSON, "r") as f:
        shelter_info = json.load(f)

    def find_shelter(object_id):
        for shelter in shelter_info["features"]:
            if (shelter["properties"]["OBJECTID"] == object_id):
                return shelter

    for mode in ["walk", "drive", "transit"]:
        output = UPDATED_ROUTES_TEMPLATE % mode
        print("Creating %s" % output)

        with open(ROUTES_JSON, "r") as f_in, open(output, "w") as f_out:
            docs = []

            for line in f_in.readlines():
                doc = json.loads(line)
                doc.pop("_id")
                for shelter in doc["shelters"]:
                    shelter["coordinates"] = find_shelter(shelter["objectid"])["geometry"]["coordinates"]
                doc["shelters"] = sorted(
                    doc["shelters"],
                    key = lambda shelter: (
                        shelter["routes"][mode]
                        and shelter["routes"][mode]["duration"]
                        # arbitrarily large number pushes items without calculated
                        # routes to the end of the list
                        or 1e10
                    )
                )
                docs.append(doc)

            json.dump(docs, f_out, indent = 4)

class Renderer(object):

    def __init__(self):
        print("Loading acs5 csv")
        self.acs5 = pandas.read_csv(ACS5_CSV)
        self.acs5.index = self.acs5.pop("GEOID")

        self.colormap = cm.get_cmap(COLORMAP)

        self.mongo = pymongo.MongoClient()

    def render(self, mode, n_closest,
               exclude_shelters_from_zones = EVAC_EXCLUDE):

        print("Rendering %s, %d closest shelters" % (mode, n_closest))
        blockgroup_collection = self.mongo[BG_DB][BG_COLLECTION]
        figure, axis = pyplot.subplots()

        # Structure:
        #     key: String representation of shelter object ID
        #     value: Population that that shelter serves
        shelter_pops = {}

        # Contains dictionaries with the following indices:
        # avg_travel: The average travel time, or False if no routes could be
        #     made to this block group
        # geoid: GEOID string
        # geojson: GeoJSON dict
        # population: population int
        blockgroups = []

        bg_to_shelter_lines = []

        with open(BOSTON_GEOJSON, "r") as f:
            boston_polygon = shapely.geometry.shape(json.load(f))

        # Reduce the number of spatial calculations
        # Additionally, excluded_shelters can be used for stylistic reasons
        excluded_shelters = set()
        not_excluded_shelters = set()

        exclude_polygon = False
        if (type(exclude_shelters_from_zones) is list):
            exclude_polygon = util.union_evac_zones(exclude_shelters_from_zones)

        with open(UPDATED_ROUTES_TEMPLATE % mode, "r") as f:
            docs = json.load(f)

        for doc in docs:
            if (not doc["blockgroup"]["geoid"] in IGNORE_GEOIDS):

                bg_geoid = doc["blockgroup"]["geoid"]

                if (not boston_polygon.contains(
                    shapely.geometry.Point(doc["blockgroup"]["centroid"])
                )):
                    print("skipping block group %s" % bg_geoid)
                    continue

                bg_acs5_geoid = ACS5_GEOID_PREFIX + bg_geoid
                bg_pop = self.acs5[ACS5_POP_TOTAL_COL][bg_acs5_geoid]

                # list of the durations of the n closest paths, if any. ignores
                # all entries where the route is False; if the length is zero,
                # no routes could be made from this block group
                """
                travel_times = [
                    mode["duration"]
                    for mode in list(filter(
                        lambda x: x is not False,
                        [
                            shelter["routes"][mode] for shelter in doc["shelters"]
                        ]
                    ))[:n_closest]
                ]
                """

                travel_times = []

                for shelter in doc["shelters"]:

                    if (shelter["routes"][mode] is not False):

                        if (exclude_polygon):
                            object_id = shelter["objectid"]

                            if (object_id in excluded_shelters):
                                continue
                            elif (object_id in not_excluded_shelters):
                                pass
                            elif (exclude_polygon.contains(
                                shapely.geometry.Point(shelter["coordinates"])
                            )):
                                excluded_shelters.add(object_id)
                                continue
                            else:
                                not_excluded_shelters.add(object_id)

                        travel_times.append(
                            shelter["routes"][mode]["duration"]
                        )

                        object_id_str = str(shelter["objectid"])
                        if (object_id_str in shelter_pops):
                            shelter_pops[object_id_str] += bg_pop
                        else:
                            shelter_pops[object_id_str] = bg_pop

                        bg_to_shelter_lines.append([
                            shelter["coordinates"],
                            doc["blockgroup"]["centroid"]
                        ])

                    if (len(travel_times) == n_closest):
                        break

                if (len(travel_times) > 0):
                    bg_avg_travel = sum(travel_times) / len(travel_times)
                else:
                    bg_avg_travel = False

                print(bg_geoid, bg_pop, bg_avg_travel)

                blockgroups.append({
                    "avg_travel": bg_avg_travel / 60,
                    "geoid": bg_geoid,
                    "geojson": blockgroup_collection.find_one({
                        "properties.GEOID": bg_geoid
                    })["geometry"]["geometries"][1],
                    "population": bg_pop
                })

        print("excluded shelters: %s" % excluded_shelters)
        print("Populations served by shelters: %s" % shelter_pops)

        axis.set_xlim([-71.2, -70.9])
        axis.set_ylim([42.21, 42.42])

        ## blockgroup plotting
        bg_travel = [blockgroup["avg_travel"] for blockgroup in blockgroups]
        min_bg_travel = min(bg_travel)
        max_bg_travel = max(bg_travel)
        bg_travel_range = max_bg_travel - min_bg_travel

        colormap_normalize = colors.Normalize(min_bg_travel, max_bg_travel)

        for blockgroup in blockgroups:
            if blockgroup["avg_travel"]:
                facecolor = self.colormap(
                    colormap_normalize(blockgroup["avg_travel"])
                )
            else:
                # rgb conversion is done for the value transformation
                facecolor = colors.to_rgb(COLOR_INACCESSIBLE)

            #edgecolor_hsv = colors.rgb_to_hsv(facecolor[:3])
            #edgecolor_hsv[2] *= 0.5

            axis.add_patch(descartes.PolygonPatch(
                blockgroup["geojson"],
                facecolor = facecolor,
                #edgecolor = colors.hsv_to_rgb(edgecolor_hsv)
                edgecolor = facecolor
            ))

        # plot Boston city boundaries
        axis.add_patch(descartes.PolygonPatch(
            shapely.geometry.mapping(boston_polygon),
            facecolor = "none",
            edgecolor = "#bbbbbb",
            linewidth = 0.5
        ))

        ## shelter plotting
        shelter_pops_values = [
            shelter_pops[objectid] / 3
            for objectid in shelter_pops
        ]
        min_pop = min(shelter_pops_values)
        max_pop = max(shelter_pops_values)
        pop_range = max_pop - min_pop

        for shelter in doc["shelters"]:
            object_id_str = str(shelter["objectid"])

            if (object_id_str in shelter_pops):
                pop = shelter_pops[object_id_str]
                pop_normalized = (pop - min_pop) / pop_range
                last_shelter = axis.plot(
                    shelter["coordinates"][0],
                    shelter["coordinates"][1],
                    marker = "o",
                    markersize = SHELTER_MIN_SIZE + (
                        pop_normalized * (SHELTER_MAX_SIZE - SHELTER_MIN_SIZE)
                    ),
                    color = SHELTER_COLOR
                )

            # excluded by query
            elif (shelter["objectid"] in excluded_shelters):
                last_shelter_excluded = axis.plot(
                    shelter["coordinates"][0],
                    shelter["coordinates"][1],
                    marker = "o",
                    markersize = SHELTER_MIN_SIZE,
                    color = SHELTER_COLOR_EXCLUDED
                )

            # not among the n closest of any block group
            else:
                last_shelter_unused = axis.plot(
                    shelter["coordinates"][0],
                    shelter["coordinates"][1],
                    marker = "o",
                    markersize = SHELTER_MIN_SIZE,
                    color = SHELTER_COLOR_UNUSED
                )

        ## lines from shelters to block groups
        axis.add_collection(collections.LineCollection(
            bg_to_shelter_lines,
            colors = SHELTER_LINK_COLOR,
            linewidths = SHELTER_LINK_LINEWIDTH,
            alpha = SHELTER_LINK_OPACITY
        ))

        ## final tweaks
        pyplot.title(
            "Relationships between block groups and the %d closest "
            "shelters; mode of transit = %s" % (n_closest, mode)
        )

        mappable = pyplot.cm.ScalarMappable(colormap_normalize, COLORMAP)
        mappable.set_array([min_bg_travel, max_bg_travel])
        colorbar = figure.colorbar(mappable)
        colorbar.set_label("Average transit time, in minutes")

        ## legend
        pyplot.legend(
            loc = "lower right",
            handles=[
                lines.Line2D(
                    [], [], linewidth = 0, marker = "o",
                    markersize = LEGEND_MARKER_SIZE,
                    color = SHELTER_COLOR_EXCLUDED,
                    label = "Excluded shelter"
                ),
                lines.Line2D(
                    [], [], linewidth = 0, marker = "o",
                    markersize = LEGEND_MARKER_SIZE,
                    color = SHELTER_COLOR,
                    label = "Active shelter"
                ),
                lines.Line2D(
                    [], [], linewidth = 0, marker = "o",
                    markersize = LEGEND_MARKER_SIZE,
                    color = SHELTER_COLOR_UNUSED,
                    label = "Unused shelter"
                ),

                patches.Patch(
                    color = COLOR_INACCESSIBLE,
                    label = "No access to shelters"
                )
            ]
        )

        pyplot.show()
        pyplot.close()

if (__name__ == "__main__"):
    if (not os.path.isdir(OUTDIR)):
        os.mkdir(OUTDIR)

    #update_routes()
    r = Renderer()
    #r.render("walk", 3, ["ZONE A", "ZONE B"])
    r.render("transit", 3)
